### ISSUE TITLE
Image doesn't build with Dockerfile.centos due to Centos EOL

### ISSUE THREAD

**Issue by AAbakumov** [WebSpellChecker/wproofreader-docker#59]
I noticed that image stopped building with Dockerfile.centos due to OS EOL. Their dockerhub profile is DEPRECATED. Also there is no official dockerhub repository of Centos Stream, so I guess we need to search for some open-source alternative of Fedora.

https://hub.docker.com/_/centos
https://github.com/docker-library/official-images/pull/17094

<img width="1594" alt="Screenshot 2024-07-11 at 20 11 26" src="https://github.com/user-attachments/assets/80914022-8d7e-4441-b709-9b668ccbf0fb">

**Comment by jshaptala** [comment]
Decided to remove Dockerfile.centos Dockerfile and update README accordingly.
